<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright (c) 2025 TrekkieEnderman
  ~
  ~     This program is free software: you can redistribute it and/or modify
  ~     it under the terms of the GNU General Public License as published by
  ~     the Free Software Foundation, either version 3 of the License, or
  ~     (at your option) any later version.
  ~
  ~     This program is distributed in the hope that it will be useful,
  ~     but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~     GNU General Public License for more details.
  ~
  ~     You should have received a copy of the GNU General Public License
  ~     along with this program.  If not, see <https://www.gnu.org/licenses/>.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>advancedgift-parent</artifactId>
        <groupId>io.github.TrekkieEnderman</groupId>
        <version>parent</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>advancedgift-core</artifactId>
    <version>2.0</version>
    <build>
        <directory>../target</directory>
        <finalName>AdvancedGift-${project.version}</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.6.1</version>
                <configuration>
                    <relocations>
                        <relocation>
                            <pattern>org.bstats</pattern>
                            <shadedPattern>io.github.TrekkieEnderman.advancedgift.bstats</shadedPattern>
                        </relocation>
                    </relocations>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <targetPath>.</targetPath>
                <filtering>true</filtering>
                <directory>src/main/resources</directory>
                <includes>
                    <include>plugin.yml</include>
                    <include>config.yml</include>
                </includes>
            </resource>
            <resource>
                <filtering>false</filtering>
                <directory>src/main/resources/translations</directory>
                <targetPath>translations</targetPath>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>lang-utils-repo</id>
            <url>https://raw.github.com/MascusJeoraly/LanguageUtils/mvn-repo/</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.11-R0.1-SNAPSHOT</version>
            <exclusions>
                <!-- Screw you Maven, stop picking this over PaperMC! -->
                <exclusion>
                    <groupId>org.spigotmc</groupId>
                    <artifactId>spigot-api</artifactId>
                </exclusion>
            </exclusions>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-bukkit</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.bstats</groupId>
            <artifactId>bstats-base</artifactId>
            <version>3.0.0</version>
            <scope>compile</scope>
        </dependency>
        <!-- ArtMap has to be compiled locally -->
        <dependency>
            <groupId>com.gitlab.blockstack</groupId>
            <artifactId>ArtMap</artifactId>
            <version>3.9.24</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>
</project>