name: AdvancedGift
main: io.github.TrekkieEnderman.advancedgift.AdvancedGift
version: ${project.version}
author: "TrekkieEndermom (Old name: TrekkieEnderman)"
softdepend: [LangUtils, ArtMap]
api-version: 1.13

commands:
  gift:
    description: "Send your friend or foe a gift, anywhere and anytime, in an instant!"
    aliases: [sendgift, giftsend]
  togglegift:
    description: "Enable or disable your ability to receive gifts from everyone."
    usage: "/togglegift <on/off>"
    aliases: [gifttoggle, tg, gt]
  agreload:
    description: "Reload the AdvancedGift config."
    aliases: [agr]
  giftspy:
    description: "Spy on the gift exchanges to catch the offensive ones."
    aliases: [gspy]
  giftblock:
    description: "Block gifts from a player you dislike or find annoying! ...Or unblock them."
    usage: "/giftblock [player]"
    aliases: [blockgift, gblock, giftunblock, unblockgift, gunblock, ungblock]
  giftblocklist:
    description: "Lists the players you've blocked gifts from, or clear the list."
    usage: "/giftblocklist (clear)"
    aliases: [gblocklist, gblist]