name: AdvancedGift
main: io.github.TrekkieEnderman.advancedgift.AdvancedGift
version: ${project.version}
author: "TrekkieEndermom (Old name: TrekkieEnderman)"
softdepend: [LangUtils, ArtMap]
api-version: 1.13

commands:
  gift:
    description: "Send your friend or foe a gift, anywhere and anytime, in an instant!"
    aliases: [sendgift, giftsend]
  togglegift:
    description: "Enable or disable your ability to receive gifts from everyone."
    usage: "/togglegift <on/off>"
    aliases: [gifttoggle, tg, gt]
  agreload:
    description: "Reload the AdvancedGift config."
    aliases: [agr]
  giftspy:
    description: "Spy on the gift exchanges to catch the offensive ones."
    aliases: [gspy]
  giftblock:
    description: "Block gifts from a player you dislike or find annoying!"
    usage: "/giftblock [player]"
    aliases: [blockgift, gblock]
  giftunblock:
    description: "Unblock a player, allowing them to send you gifts again."
    usage: "/giftunblock [player]"
    aliases: [unblockgift, gunblock, ungblock]
  giftblocklist:
    description: "Lists the players you've blocked gifts from, or clear the list."
    usage: "/giftblocklist (clear)"
    aliases: [gblocklist, gblist]

permissions:
  advancedgift.gift.send:
    description: Allows sending gifts
    default: true
    children:
      advancedgift.gift.receive: true
  advancedgift.gift.message:
    description: Allows attaching messages to gifts
    default: true
  advancedgift.gift.spy:
    description: Allows spying on gift exchanges
    default: op
  advancedgift.bypass.cooldown:
    description: Allows bypassing the gift cooldown
    default: false
  advancedgift.bypass.world.restriction:
    description: Allows bypassing the restriction on sending gifts between groups of worlds
    default: false
  advancedgift.bypass.world.blacklist:
    description: Allows sending and receiving gifts while in a blacklisted world
    default: false
  advancedgift.bypass.vanish:
    description: Allows sending gifts to hidden players
    default: op
  advancedgift.reload:
    description: Allows reloading AdvancedGift's configuration files
    default: op